blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, \
    BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog'),
    path('blog/view/<int:pk>/', BlogDetailView.as_view(), name='article'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/update/<int:pk>/', BlogUpdateView.as_view(), name='article_update'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='article_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from catalog.models import NULLABLE


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок', **NULLABLE)
    slug = models.CharField(max_length=100, verbose_name='URL', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое', **NULLABLE)
    preview = models.ImageField(upload_to='blog/', verbose_name='Превью', **NULLABLE)
    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_publish = models.BooleanField(default=True, verbose_name='Признак публикации')
    count_of_views = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ('title',)

blog/forms.py
from blog.models import Blog
from catalog.forms import StyleFormMixin
from django import forms


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        exclude = ('count_of_views',)

blog/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from blog.forms import BlogForm
from blog.models import Blog


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_of_views += 1
        self.object.save()
        if self.object.count_of_views == 100:
            send_mail(subject="hi there", message="good job", from_email=settings.EMAIL_HOST_USER,
                      recipient_list=[settings.EMAIL_HOST_USER])

        return self.object


class BlogListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Blog
    permission_required = 'blog.view_blog'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_publish=True)
        return queryset


class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog')
    permission_required = 'blog.add_blog'

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    permission_required = 'blog.change_blog'

    def get_success_url(self):
        return reverse('blog:article', args=[self.object.pk])


class BlogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Blog
    permission_required = 'blog.delete_blog'
    success_url = reverse_lazy('blog:blog')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Удаление товара
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить товар {{ object.title|title }}?</p>
                <button type="submit" class="btn btn-danger">
                    Удалить
                </button>
                <a class="btn btn-outline-warning" href="{% url 'blog:blog' %}">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tag %}
{% block content %}
<div class="col">
    <a class="btn btn-outline-info-link" href="{% url 'blog:blog' %}">Назад</a>
</div>
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-tite">
                        {{ object.title|title }} ({{ object.slug }})
                    </h3>
                </div>
                <div class="card-body">
                    <img class="card-img-top"
                         src=" {{ object.preview|mymedia }} "
                         alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">{{ object.content|title }}</p>
                    </div>
                    <div class="card-body">
                        <div class="card-text">Просмотры: {{ object.count_of_views }}</div>
                    </div>
                </div>
                <div class="card-footer">
                    <a class="btn btn-link" href="{% url 'blog:article_update' object.pk %}">Изменить</a>
                    <a class="btn btn-outline-danger float-right"
                       href="{% url 'blog:article_delete' object.pk %}">Удалить</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Редактирование
                {% else %}
                Добавление статьи
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">
                    {% if object %}
                    Редактировать
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tag %}
{% block content %}
<div class="col-12 mb-5">
    <a href="{% url 'blog:blog_create' %}" class="btn btn-primary">Написать статью</a>
</div>
    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h3 class="card-title">
                        {{ object.title|title }}
                    </h3>
                    <img class="card-img-top"
                         src="{{ object.preview|mymedia }}"
                         alt="Card image cap">
                </div>
                <div class="card-body">
                    <p class="card-text">{{ object.content|my_description }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'blog:article' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary ">Читать</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}