blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, \
    BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog'),
    path('blog/view/<int:pk>/', BlogDetailView.as_view(), name='article'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/update/<int:pk>/', BlogUpdateView.as_view(), name='article_update'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='article_delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from catalog.views import contacts, ProductListView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, ProductDetailView, \
    VersionCreateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('contacts/', contacts, name='contacts'),
    path('product/view/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='view_product'),
    path('product/create/', never_cache(ProductCreateView.as_view()), name='product_create'),
    path('product/update/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('version_create/', VersionCreateView.as_view(), name='version_create'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.conf import settings
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    category_name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')

    def __str__(self):
        return f'{self.category_name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('category_name',)


class Product(models.Model):
    product_name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    image = models.ImageField(upload_to='product/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория',
                                 **NULLABLE)
    price_for_one = models.IntegerField(verbose_name='Цена за штуку', **NULLABLE)
    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    last_modified_date = models.DateTimeField(auto_now=True,
                                              verbose_name='Дата последнего изменения')

    is_published = models.BooleanField(default=False, verbose_name='Опубликован')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                              verbose_name='владелец')

    def __str__(self):
        return f'{self.product_name} ({self.category})'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('product_name',)
        permissions = [(
            "change_published_status",
            "Can cancel publication of a product"
        ),
            ("change_product_description",
             "Can change product description"
             ),
            (
                "change_category",
                "Can change category"
            )

        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    number_version = models.PositiveIntegerField(verbose_name='номер версии', **NULLABLE)
    name_version = models.CharField(max_length=150, verbose_name='название версии', **NULLABLE)

    is_active = models.BooleanField(default=True, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.name_version} {self.number_version}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'
        ordering = ('name_version',)

catalog/forms.py
from django import forms

from catalog.models import Product, Version, Category


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CategoryForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('owner',)

    def clean_product_name(self):
        cleaned_data = self.cleaned_data['product_name']
        f = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
             'радар',)
        if cleaned_data in f:
            raise forms.ValidationError('Недопустимое имя для продукта')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        f = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
             'радар',)
        if cleaned_data in f:
            raise forms.ValidationError('Недопустимое слова для описания продукта')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'


class ModeratorProductForm(ProductForm):
    """
    Класс создания формы для редактирования модератором
    """

    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published')

catalog/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, \
    DetailView

from catalog.forms import ProductForm, VersionForm, ModeratorProductForm
from catalog.models import Product, Category, Version


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset


class ProductListView(LoginRequiredMixin, ListView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_form_class(self):
        if self.request.user == self.object.owner:
            return ProductForm
        elif self.request.user.groups.filter(name='moderator'):
            return ModeratorProductForm
        else:
            raise Http404('Вы не являетесь владельцем данного товара')


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:index')

    def get_object(self, queryset=None, *args, **kwargs):
        object_data = super().get_object(*args, **kwargs)
        if self.request.user == object_data.owner:
            return object_data
        else:
            raise Http404('Вы не являетесь владельцем данного товара')


class VersionCreateView(LoginRequiredMixin, CreateView):
    template_name = 'catalog/product_form.html'
    model = Version
    form_class = VersionForm
    permission_required = 'catalog.add_version'
    success_url = reverse_lazy('catalog:index')


@login_required
def contacts(request):
    context = {
        'title': 'Контакты',
    }
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        with open('feedback.txt', 'w') as f:
            f.write(f'User_name: {name}\nContact_number: {phone}\n"{message}"\n')

    return render(request, 'catalog/contacts.html', context)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        {% include 'catalog/includes/inc_menu.html' %}
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</main>


<footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; {% now 'Y'%}</small>
        </div>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tag %}
{% block content %}
<div class="col">
    <a class="btn btn-outline-info-link" href="{% url 'catalog:blog' %}">Назад</a>
</div>
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-tite">
                        {{ object.title|title }} ({{ object.slug }})
                    </h3>
                </div>
                <div class="card-body">
                    <img class="card-img-top"
                         src=" {{ object.preview|mymedia }} "
                         alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">{{ object.content|title }}</p>
                    </div>
                    <div class="card-body">
                        <div class="card-text">Просмотры: {{ object.count_of_views }}</div>
                    </div>
                </div>
                <div class="card-footer">
                    <a class="btn btn-link" href="{% url 'catalog:article_update' object.pk %}">Изменить</a>
                    <a class="btn btn-outline-danger float-right"
                       href="{% url 'catalog:article_delete' object.pk %}">Удалить</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tag %}
{% block content %}
<div class="col-12 mb-5">
    <a href="{% url 'catalog:blog_create' %}" class="btn btn-primary">Написать статью</a>
</div>
    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h3 class="card-title">
                        {{ object.title|title }}
                    </h3>
                    <img class="card-img-top"
                         src="{{ object.preview|mymedia }}"
                         alt="Card image cap">
                </div>
                <div class="card-body">
                    <p class="card-text">{{ object.content|my_description }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'catalog:article' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary ">Читать</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/category_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Удаление категории
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить категорию {{ object.category_name }}?</p>
                <button type="submit" class="btn btn-danger">
                    Удалить
                </button>
                <a class="btn btn-outline-warning" href="{% url 'catalog:categories' %}">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row text-start">
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>USA</td>
                    </tr>
                    <tr>
                        <td class="w-25">ИНН</td>
                        <td>91-1144442</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>Redmond,WA,98052-6399</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Обратная связь</label>
                        <textarea type="text" name="message" class="form-control" id="message" placeholder="Оставьте сообщение" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Удаление товара
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить товар {{ object.product_name }}?</p>
                <button type="submit" class="btn btn-danger">
                    Удалить
                </button>
                <a class="btn btn-outline-warning" href="{% url 'catalog:index' %}">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tag %}
{% block content %}
<div class="col">
    <a class="btn btn-outline-info-link" href="{% url 'catalog:index' %}">Назад</a>
</div>
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-tite">
                        {{ object.product_name|title }}
                    </h3>
                </div>
                <div class="card-body">
                    <img class="card-img-top"
                         src="{{ object.image|mymedia }}"
                         alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">{{ object.category|title }}</p>
                        <h1 class="card-title pricing-card-title">{{ object.price_for_one }} руб.<small
                                class="text-body-secondary fw-light"></small></h1>
                    </div>
                </div>
                <div class="card-footer">
                    <ul class="list-unstyled mt-3 mb-4 text-center m-3">
                        <li>{{ object.description }}</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Редактирование
                {% else %}
                Добавление товара
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">
                    {% if object %}
                    Редактировать
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Версия Продукта
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% if not forloop.last %}
                <hr>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tag %}
{% block content %}

<div class="row">
    {% if perms.catalog.add_product %}
    <div class="col-6 mb-5">
        <a class="btn btn-primary" href="{% url 'catalog:product_create' %}">Добавить продукт</a>
        <a class="btn btn-primary" href="{% url 'catalog:version_create' %}">Добавить версию продукта</a>
    </div>
    {% endif %}
    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">{{ object.product_name|title }}</h4>
                </div>
                <img class="card-img-top"
                     src="{{ object.image|mymedia }}"
                     alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">{{ object.category|title }}</p>
                    <p class="card-text">{{ object.description|my_description }}</p>
                    <h1 class="card-title pricing-card-title">{{ object.price_for_one }} руб.<small
                            class="text-body-secondary fw-light"></small></h1>
                </div>
                <div class="card-footer">
                    <div class="btn-group ">
                        <a href="{% url 'catalog:view_product' object.pk %}" type="button"
                           class="btn btn-sm  btn-outline-primary">view</a>
                        {% for group in request.user.groups.all %}
                        {% if group.name == "moderator" %}
                        <a href="{% url 'catalog:product_update' object.pk %}" type="button"
                           class="btn btn-sm  btn-outline-primary">edit</a>
                        {% endif %}
                        {% endfor %}
                        {% if request.user == object.owner %}
                        <a href="{% url 'catalog:product_delete' object.pk %}" type="button"
                           class="btn btn-sm  btn-outline-danger">delete</a>
                        {% endif %}
                    </div>
                    <div>
                        <span class="text-muted">Продавец: {{ object.owner|default:'no name' }}</span>
                        {% for version in object.version_set.all %}
                        {% if version.is_active %}
                        <a> активная версия {{ version.number }}</a>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}